### Create 
POST http://localhost:3000/products.json
Content-Type: application/json

{
"name": "Mobile",
"price": "300",
"image_url": "https://www.techandroids.com/wp-content/uploads/2018/06/Asus-ROG-Phone-image-1.jpg",
"description": "Asus' latest gaming mobile phone"
}

### Index
GET http://localhost:3000/products.json

### Show
GET http://localhost:3000/products/1.json

### Update 

PATCH http://localhost:3000/products/6.json
Content-Type: application/json

{
  "image_url" : "https://images.nintendolife.com/news/2018/07/the_nintendo_switch_is_headed_to_turkey_but_will_cost_customers_almost_usd500/attachment/0/original.jpg",
  "description" : "Nintendo's lamest portable console"
}

### Delete
DELETE http://localhost:3000/products/5.json